// iconMap.ts
import {
  IconCamera,
  IconChartBar,
  IconDatabase,
  IconFileAi,
  IconFileDescription,
  IconHelp,
  IconReport,
  IconSettings,
  IconUsers,
  IconUserSearch,
  IconListNumbers,
  IconBuilding,
  IconClipboardList,
  IconFileReport,
  IconReportMoney,
  IconAlertTriangle,
  IconLink,
  IconHome,
  IconShield,
  IconFileText,
  IconTractor,
  IconHash,
  IconCirclePlus,
  IconFileSpreadsheet
} from "@tabler/icons-react";

export const ICON_MAP: Record<string, React.ElementType> = {
  IconCamera,
  IconChartBar,
  IconDatabase,
  IconFileAi,
  IconFileDescription,
  IconHelp,
  IconReport,
  IconSettings,
  IconUsers,
  IconUserSearch,
  IconListNumbers,
  IconBuilding,
  IconClipboardList,
  IconFileReport,
  IconReportMoney,
  IconAlertTriangle,
  IconLink,
  // Nuevos iconos mapeados desde la base de datos
  home: IconHome,
  users: IconUsers,
  shield: IconShield,
  building: IconBuilding,
  "file-text": IconFileText,
  factory: IconTractor,
  hash: IconHash,
  "plus-circle": IconCirclePlus,
  "file-spreadsheet": IconFileSpreadsheet,
  "alert-triangle": IconAlertTriangle,
  "bar-chart": IconChartBar
};
